//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user33Entities : DbContext
    {
        public user33Entities()
            : base("name=user33Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address2> Address2 { get; set; }
        public virtual DbSet<Order2> Order2 { get; set; }
        public virtual DbSet<Product2> Product2 { get; set; }
        public virtual DbSet<Role2> Role2 { get; set; }
        public virtual DbSet<User2> User2 { get; set; }
    }
}
