//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user33Entities : DbContext
    {
        public user33Entities()
            : base("name=user33Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address3> Address3 { get; set; }
        public virtual DbSet<Order3> Order3 { get; set; }
        public virtual DbSet<Product3> Product3 { get; set; }
        public virtual DbSet<Role3> Role3 { get; set; }
        public virtual DbSet<User3> User3 { get; set; }
    }
}
